volumes:
  postgres:
  redis:

services:
  app:
    image: node:20.17.0
    container_name: "rocketseat-nodejs-desafio-05-fast-feet-api"
    ports:
      - "9999:9999"
      - "3333:3333"
      - "5555:5555"
      - "51204:51204"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "node index.mjs"

  db:
    image: bitnami/postgresql
    container_name: "rocketseat-nodejs-desafio-05-fast-feet-db"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: fastfeet
    volumes:
      - postgres:/data/postgres

  redis-05:
    image: redis
    container_name: "rocketseat-nodejs-desafio-05-fast-feet-redis"
    ports:
      - "6375:6379"
    volumes:
      - redis:/data
